name: 'CI'     # Name of the action.
on: [push] 

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'
    - name: list command output  
      run: |
        ls -l
        echo 'abhijit'
